### ISSUE TITLE
could not find "compute_ap"

### ISSUE THREAD

**Issue by davidz123** [imatge-upc/retrieval-2016-icmr#10]
I could not find the file “compute_ap” used in evaluate_Oxf_Par.py
Do you upload the  @file?
@xavigiro

**Comment by evamohe** [comment]
The file is located in [retrieval-2016-icmr/oxford](https://github.com/imatge-upc/retrieval-2016-icmr/tree/master/oxford).

**Comment by davidz123** [comment]
> The file is located in [retrieval-2016-icmr/oxford](https://github.com/imatge-upc/retrieval-2016-icmr/tree/master/oxford).

One more question： cause I cannot read the source code of compute_ap， I  am wondering if the good ok and even junk class of Paris dataset are  all counted in detected？

**Comment by evamohe** [comment]
You can find the source code in the original [Oxford dataset ](http://www.robots.ox.ac.uk/~vgg/data/oxbuildings/).
