### ISSUE TITLE
Problem in A_feature_extraction.py

### ISSUE THREAD

**Issue by willard-yuan** [imatge-upc/retrieval-2016-icmr#2]
The line [L363](https://github.com/imatge-upc/retrieval-2016-icmr/blob/master/bow_pipeline/A_feature_extraction.py#L363) in `A_feature_extraction.py` is superfluous, and it need to comment to make it run successfully.

**Comment by hurricane2018** [comment]
I modified the corresponding path in the settings.json file, then ran it. However, an error appeared: " NameError: name 'pathDB' is not defined " .
My question is how did you define pathDB ? is it the prototxt file ?

Thank you very much!

**Comment by evamohe** [comment]
Hi @hurricane2018,

If you are running the 'A_feature_extraction.py', pathDB should be automatically created by the 'LeveldbStorer' based on the 'featuresDB' and 'input_size' specified in your settings. Please, make sure you have specified those parameters in the settings file.

I also encourage you to take a look to our recent paper ["Saliency Weighted Convolutional Features for Instance Search"](https://imatge-upc.github.io/salbow/) where you can find an updated (and probably cleaner/easy to use) version of the code.

Best,
Eva

**Comment by hurricane2018** [comment]
Dear Eva:

     Thank you for your reply.  I have modified the values in
settings.json. However, the default value of pathDB is " pathDB='/media/eva/Eva
Data/icmr_results/trecvid_subset/features/vgg16/768_576/pool5_db ".
Actually, I don't know what is pool5_db. Is pool5_db a file folder ?

Thank you very much!


2018-02-15 4:14 GMT-05:00 Eva Mohedano <notifications@github.com>:
